### PR TITLE
Improve date parser

### PR DESCRIPTION
**Pull request by jomey**
Hardcode the used timezone for dateparser to be in 'UTC' making it independent from the set time one of the operating system. The returned value by the method will remain timezone unaware.

### CODE REVIEW

**Comment by jomey** [comment]
@scotthavens - Here the PR with the date parsing updates we talked about on Friday.

**Comment by scotthavens** [comment]
Based on the tests, a value with a timezone will be converted to UTC, wouldn't that warrant the tzinfo to remain? Then the user would know that it's not in MST but was converted. This should be documented in the doc's. @micahjohnson150  would know the best place for that.

What would happen if the timezone wasn't passed? It should just return the date as is correct? This is our main use for the inicheck date.

**Comment by jomey** [comment]
> Based on the tests, a value with a timezone will be converted to UTC, wouldn't that warrant the tzinfo to remain? 

The settings of `'RETURN_AS_TIMEZONE_AWARE': False`, when using parse will always return a tz unaware `datetime` object. Added more tests to show this behavior.

> What would happen if the timezone wasn't passed? It should just return the date as is correct? This is our main use for the inicheck date.

Same as above. A string with or without a TZ info will always return a TZ unaware object.

Maybe there should be a warning/info shown that could inform the user of the change into UTC, once a timezone was given with the string? I assume that this is not a use case so far and people have not tried doing so.

**Comment by scotthavens** [comment]
Thanks for filling the tests and doc string out. I agree that the timezone is not a full use case yet and most of it is for the non tz aware date strings. I'd like to get @micahjohnson150 opinion on this to make sure we're not missing anything in inicheck.

If we were all on UTC things would be so much easier!

**Comment by micahjohnson150** [comment]
I am not completely sure I am following this but it sounds like the HPC was in MST and the data was in UTC. This caused some problems converting the config dates entries and it was being converted to MST? Just making sure I understand.

As for documenting in RTD, a good place would be somewhere under L55 in docs/master_config.rst 

Would we want to create a timezone aware checker? The checker has access to the whole config so we could make it depend on a timezone. Similar to how we made orderdatetime pair? Where they are checked against the corresponding end/start dates?

**Comment by jomey** [comment]
> I am not completely sure I am following this but it sounds like the HPC was in MST and the data was in UTC. This caused some problems converting the config dates entries and it was being converted to MST? 

Micah, this was the email thread going around last Friday (I think you were part of this).

Here the situation:
- HPC node running in MST
-  I was running Katana through a Singularity container (converted from the Docker image, as HPC does not allow Docker)
- Singularity seems to behave differently as it does not return the set timezone within the image, but the timezone of the node it is executed on.
- When parsing the date set in in the .ini, the `dateparser` library came back with this error:
```ValueError: Timezone offset does not match system offset: 0 != -21600. Please, check your config files.```

The behavior comes from the library, where it uses the timezone set on the host to parse it. 

Motivation here is to make inicheck independent from the running hosts timezone and always treat the given times as UTC. It only should check, whether the set date is parsable and then leave it to the libs (WRF, SMRF, AWSM) to make them timezone aware based of the optional timezone info.

Hope that clarifies the intention.

**Comment by micahjohnson150** [comment]
@jomey thanks!

@scotthavens how will this affect SMRF when a user assigns a timezone other than UTC?

**Comment by scotthavens** [comment]
Currently, @jomey  is working through all the timezone fun so it shouldn't affect SMRF based on his last changes.

**Comment by jomey** [comment]
I did some work around timezones in SMRF here: USDA-ARS-NWRC/smrf/pull/145

**Comment by micahjohnson150** [comment]
As in he is using this with SMRF now? or as in we won't update inicheck in smrf to utilize this?

**Comment by micahjohnson150** [comment]
The only fallout I see from this is that the backup configs will have the converted UTC time in them vs what the user originally put in the config. Are we ok with this behavior?

**Comment by scotthavens** [comment]
@micahjohnson150 I'm okay with this behavior. While it may not be ideal, I don't see a simple fix for this since time zones are not easy to deal with. As long as it's stated in the doc's that this will be converted to UTC then that should be fine.

Anyways, as @jomey showed in the tests, the way we currently use it will be unaffected. Since we specify `2020-10-01 00:00` without any tz attached, it will return `2020-10-01 00:00`. They only change will be when the timezone code is specified. If the user specifies a timezone like that then they should be aware of what will happen. But the way it's used now, the date should be unchanged but parsed. Then it would be up to SMRF to read the time zone value and localize the date to the timezone.

**Comment by micahjohnson150** [comment]
Thanks @jomey for working through the TZ nightmare!

**Comment by scotthavens** [comment]
image

And @jomey earns a medal for his time zone work!

**Comment by micahjohnson150** [comment]
hahah where did you find that?! So perfect!

**Comment by scotthavens** [comment]
You can find anything on google!

**Comment by jomey** [comment]
😄 
Who accepts this token for 🍺 or 🍦 ?

**Comment by scotthavens** [comment]
Good for one (1) of the above next time we meet!

**Pull request merged**
